version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - $PWD/data:/var/jenkins_home
  mvn_agent:
    image: jenkins/jnlp-agent-maven:jdk11
    user: root
    container_name: mvn_agent
    command: -url http://jenkins:8080 ccaaaca9e078c79c513c169bea6cd10ab41742437644716ee2d25be0ee9bf7ff mvn_agent
    volumes:
      - $PWD/mvn_agent:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  nexus:
    image: sonatype/nexus3
    ports:
      - 8081:8081
      - 5000:5000
    volumes:
      - nexus-data:/nexus-data

volumes:
  nexus-data:
